
### Get all sensors
GET http://localhost:9000/api/v1/sensors
X-User: {{user_id}}

### Create a new sensor
POST http://localhost:9000/api/v1/sensors
X-User: {{user_id}}
Content-Type: application/json

{
  "name": "My Sensor",
  "gardenId": "{{garden_id}}"
}

> {% client.global.set("sensor_id", response.body.id); %}

### Update a sensor
PUT http://localhost:9000/api/v1/sensors/{{sensor_id}}
X-User: {{user_id}}
Content-Type: application/json

{
  "name": "My Other Sensor",
  "gardenId": "{{garden_id}}"
}

> {% client.global.set("sensor_id", response.body.id); %}

### Get a sensor
GET http://localhost:9000/api/v1/sensors/{{sensor_id}}
X-User: {{user_id}}

> {% client.global.set("sensor_id", response.body.id); %}

### Delete a sensor
DELETE http://localhost:9000/api/v1/sensors/{{sensor_id}}
X-User: {{user_id}}
