
### Get all gardens
GET http://localhost:8080/api/v1/gardens
X-User: {{user_id}}

### Create a new garden
POST http://localhost:8080/api/v1/gardens
X-User: {{user_id}}
Content-Type: application/json

{
  "name": "My Garden"
}

> {% client.global.set("garden_id", response.body.id); %}

### Update a garden
PUT http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: {{user_id}}
Content-Type: application/json

{
  "name": "My Other Garden"
}

> {% client.global.set("garden_id", response.body.id); %}

### Get a garden
GET http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: {{user_id}}

> {% client.global.set("garden_id", response.body.id); %}

### Delete a garden
DELETE http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: {{user_id}}
