
### Get all users
GET http://localhost:9000/api/v1/users
X-User: {{user_id}}

### Create a new user
POST http://localhost:9000/api/v1/users
X-User: {{user_id}}
Content-Type: application/json

{
  "name": "Jane Doe"
}

### Get a user
GET http://localhost:9000/api/v1/users/{{user_id}}
X-User: {{user_id}}

### Update a user
PUT http://localhost:9000/api/v1/users/{{user_id}}
X-User: {{user_id}}
Content-Type: application/json

{
  "gardenIds": ["{{garden_id}}"]
}

### Delete a user
DELETE http://localhost:9000/api/v1/users/{{user_id}}
X-User: {{user_id}}
