server:
  port: 9005

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/datasite-poc
    username: postgres
    password: postgres
    pool:
      enabled: true

kafka:
  bootstrapAddress: localhost:9092

logging:
  level:
    org.apache.kafka: WARN
