
### Create a new garden
POST http://localhost:8080/api/v1/gardens
X-User: user1
Content-Type: application/json

{
  "name": "My Garden"
}

> {% client.global.set("garden_id", response.body.id); %}

### Access the garden
GET http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: user1

### Update a garden
PUT http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: user1
Content-Type: application/json

{
  "name": "My Other Garden"
}

### Access the garden again
GET http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: user1

### Delete a garden
DELETE http://localhost:8080/api/v1/gardens/{{garden_id}}
X-User: user1
